[manifest]
version = "0.0.0"
dump_lua = true
priority = 1

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "eligible_card:set_edition(edition, true)"
position = 'after'
match_indent = true
payload = '''
if GameState.is_joker_consumable_key(self.config.center_key) then
    GameState.set_jokers(G.jokers.cards)
    GameState.print_jokers()
end

'''