[manifest]
version = "0.0.0"
dump_lua = true
priority = 1

# Ramen, Turtle Bean, Popcorn, Gros Michel, Cavendish, Ice Cream, Seltzer
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
SMODS.destroy_cards(self, nil, nil, true)
'''
position = 'after'
match_indent = true
payload = '''
G.E_MANAGER:add_event(Event({
    func = function()
        GameState.remove_joker(self)
        Converter.compileHand(GameState, config.automatic_url_copy)
        GameState.print_jokers()
        return true
    end
}))
'''

# Madness
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
local joker_to_destroy = #destructable_jokers > 0 and pseudorandom_element(destructable_jokers, pseudoseed('madness')) or nil
'''
position = 'after'
match_indent = true
payload = '''
G.E_MANAGER:add_event(Event({
    func = function()
        GameState.remove_joker(joker_to_destroy)
        Converter.compileHand(GameState, config.automatic_url_copy)
        GameState.print_jokers()
        return true
    end
}))
'''